import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from "next/link"
import Footer from "../components/layout/Footer/Footer";
import SearchBar from "../components/SearchBar/SearchBar";
import styles from './index.module.scss'
import SpellbookLogo from "../components/layout/SpellbookLogo/SpellbookLogo";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="gradient">
          <div className={`container ${styles.container} relative md:h-screen z-10`}>
            <div className="w-full">
              <SpellbookLogo/>

              <h2 className="font-title my-1 sm:my-3 text-2xl sm:text-3xl md:text-4xl">
                The Search Engine for EDH Combos
              </h2>

              <SearchBar onHomepage className="bg-white mt-4 md:w-2/3 h-20"/>

              <div className="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
                <Link href="/advanced-search/" className={`dark ${styles.button} button md:m-1`}>
                  Advanced Search
                </Link>
                <Link href="/syntax-guide/" className={`dark ${styles.button} button md:m-1`}>
                  Syntax Guide
                </Link>
                {/*  <RandomButton :query="query" class="random-button dark button md:m-1">*/}
                {/*  Random Combo*/}
                {/*</RandomButton>*/}
              </div>

              <div className="button-links md:flex-row md:w-2/3 m-auto flex flex-col">
                <Link href="/find-my-combos/" className={`dark ${styles.button} button md:m-1`}>
                  Find My Combos
                </Link>
                <Link v-if="featuredComboButtonText" id="featured-combos-button" href="/featured/"
                      className={`previwed-combos-button dark ${styles.button} button md:m-1`}>
                  Featured Combos
                </Link>
              </div>
            </div>
        </div>
          <Footer/>
      </div>
      </main>

    </>
  )
}
